#修改端口号
server:
  port: 9000



spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/webflux?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    pool:
      initial-size: 10
      max-idle-time: 30m
      max-size: 50

