#修改端口号
server:
  port: 9000



spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/webflux?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    #数据库连接池配置
    pool:
      initial-size: 10
      max-idle-time: 30m
      max-size: 50

